-- 코드를 입력하세요
# SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, "N") as FREEZER_YN FROM FOOD_WAREHOUSE
# WHERE WAREHOUSE_NAME = "창고_경기"
# ORDER BY WAREHOUSE_ID ASC

# SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IF(FREEZER_YN IS NULL, "N", FREEZER_YN) as FREEZER_YN FROM FOOD_WAREHOUSE
# ORDER BY WAREHOUSE_ID ASC

SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
    COALESCE(FREEZER_YN, "N") as FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE "%경기%"
ORDER BY WAREHOUSE_ID ASC